hzuapps/android-labs-2019

- students/soft1714080902133/Soft1714080902133Activity.java
> #1 提交实验一代码

- students/soft1714080902133/lab2/AndroidManifest.xml
- students/soft1714080902133/lab2/java/edu/hzuapps/androidlabs/soft1714080902133/Soft1714080902133ForgetPasswordActivity.java
- students/soft1714080902133/lab2/java/edu/hzuapps/androidlabs/soft1714080902133/Soft1714080902133HomeActivity.java
- students/soft1714080902133/lab2/java/edu/hzuapps/androidlabs/soft1714080902133/Soft1714080902133LoginActivity.java
- students/soft1714080902133/lab2/java/edu/hzuapps/androidlabs/soft1714080902133/Soft1714080902133PerfectInformationActivity.java
- students/soft1714080902133/lab2/java/edu/hzuapps/androidlabs/soft1714080902133/Soft1714080902133RegisterActivity.java
- students/soft1714080902133/lab2/java/edu/hzuapps/androidlabs/soft1714080902133/Soft1714080902133UserActivity.java
- students/soft1714080902133/lab2/java/edu/hzuapps/androidlabs/soft1714080902133/javabean/Soft1714080902133User.java
- students/soft1714080902133/lab2/layout/soft_1714080902133_forgetpasswordactivity.xml
- students/soft1714080902133/lab2/layout/soft_1714080902133_homeactivity.xml
- students/soft1714080902133/lab2/layout/soft_1714080902133_loginactivity.xml
- students/soft1714080902133/lab2/layout/soft_1714080902133_perfectinformationactivity.xml
- students/soft1714080902133/lab2/layout/soft_1714080902133_registeractivity.xml
- students/soft1714080902133/lab2/layout/soft_1714080902133_useractivity.xml
- students/soft1714080902133/lab2/layout/user_context.xml
> #2 提交实验2代码

- students/soft1714080902126/Soft1714080902126.java
- students/soft1714080902126/app/src/main/AndroidManifest.xml
- students/soft1714080902126/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902126/Soft1714080902126Activity.java
- students/soft1714080902126/app/src/main/res/layout/soft_1714080902126_activity.xml
- students/soft1714080902126/app/src/main/res/values/strings.xml
因为覆盖问题，第一次提交了一个文件，第二次提交了三个文件。请老师查看！
> #2 #363 第二次实验

- students/com1714080901129/Com1714080901129Activity.java
- students/com1714080901129/app/src/main/AndroidManifest.xml
- students/com1714080901129/app/src/main/java/edu/hzuapps/androidlabs/com1714080901129/Com1714080901129Activity.java
- students/com1714080901129/app/src/main/res/layout/com_1714080901129_activity.xml
- students/com1714080901129/app/src/main/res/values/strings.xml
> #2 提交第二次实验代码

- students/soft1714080902309/Soft1714080902309Activity.java
- students/soft1714080902309/实验二/app/src/main/AndroidManifest.xml
- students/soft1714080902309/实验二/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902309/Soft1714080902309Activity.java
- students/soft1714080902309/实验二/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902309/Soft1714080902309Activity2.java
- students/soft1714080902309/实验二/app/src/main/res/layout/soft_1714080902309_activity.xml
- students/soft1714080902309/实验二/app/src/main/res/layout/soft_1714080902309_activity2.xml
- students/soft1714080902309/实验二/app/src/main/res/values/strings.xml
这次这个app我做了两个activity，并在第一个主类中添加了按钮监听事件，实现了按钮点击跳转页面的功能。
> #2 提交实验二代码

- students/soft1714080902339/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902339/MainActivity.java
- students/soft1714080902339/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902339/SecondActivity.java
- students/soft1714080902339/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902339/Soft1714080902339Activity.java
- students/soft1714080902339/app/src/main/res/layout/activity_main.xml
- students/soft1714080902339/app/src/main/res/layout/second_activity.xml
- students/soft1714080902339/app/src/main/res/layout/soft_1714080902339_activity.xml
- students/soft1714080902339/app/src/main/res/values/strings.xml
1.主页面
2.点击主页面中的按钮跳转到第二个页面
3.点击听力、阅读......写作等按钮可以跳转到对于的网页获取资料，例如点击听力
> #4 #290 提交实验4代码文件

- students/soft1714080902421/ImageViewActivity.java
- students/soft1714080902421/Soft1714080902421MainActivity.java
- students/soft1714080902421/activity_image_view.xml
- students/soft1714080902421/soft_1714080902421_activity.xml
> #3 提交实验三代码

- students/soft1714080902421/MyTreeActivity.java
- students/soft1714080902421/SettingActivity.java
- students/soft1714080902421/Soft1714080902421MainActivity.java
- students/soft1714080902421/TotalTimeActivity.java
- students/soft1714080902421/TreePlantActivity.java
- students/soft1714080902421/activity_image_view.xml
- students/soft1714080902421/activity_main.xml
- students/soft1714080902421/activity_my_tree.xml
- students/soft1714080902421/activity_setting.xml
- students/soft1714080902421/activity_total_time.xml
- students/soft1714080902421/activity_tree_plant.xml
> #4 提交实验四代码

- students/soft1714080902115/MyApplication3/app/src/main/AndroidManifest.xml
- students/soft1714080902115/MyApplication3/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902115/Main2Activity.java
- students/soft1714080902115/MyApplication3/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902115/MainActivity.java
- students/soft1714080902115/MyApplication3/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902115/Personal_Interface.java
- students/soft1714080902115/MyApplication3/app/src/main/res/drawable/ic_launcher_background.xml
- students/soft1714080902115/MyApplication3/app/src/main/res/layout/activity_main.xml
- students/soft1714080902115/MyApplication3/app/src/main/res/layout/activity_main2.xml
- students/soft1714080902115/MyApplication3/app/src/main/res/layout/activity_personal__interface.xml
- students/soft1714080902115/MyApplication3/app/src/main/res/values/colors.xml
- students/soft1714080902115/MyApplication3/app/src/main/res/values/styles.xml
> #4 #591 提交第四次实验代码

- students/soft1714080902114/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902114/Soft1714080902114Activity.java
- students/soft1714080902114/app/src/main/res/layout/soft_1714080902114_activity.xml
> #4 #460 提交实验4代码

- students/soft1714080902232/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902232/Soft1714080902232Activity_Success.java
- students/soft1714080902232/app/src/main/res/layout/soft_1714080902232_activity_success.xml
1.界面基本布局如下：
2.文本框可输入内容，可将其存储
3.按查看按钮可提取文本内容
> #5 #533 第五次实验

- students/soft1714080902133/app/src/main/AndroidManifest.xml
- students/soft1714080902133/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902133/Soft1714080902133HomeActivity.java
- students/soft1714080902133/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902133/Soft1714080902133QueryActivity.java
- students/soft1714080902133/app/src/main/res/layout/soft_1714080902133_queryactivity.xml
- students/soft1714080902133/app/src/main/res/values/strings.xml
选择下拉框选项中的内容，再从其他界面回来后，依然保存上次选择的选项内容。
> #5 #238  提交实验5代码  宿舍缴电费app

- students/soft1714080902421/SettingActivity.java
- students/soft1714080902421/activity_setting.xml
> #5 提交实验五代码

- students/soft1714080902127/实验5/main/java/edu/hzuapps/androidlabs/soft1714080902127/Soft1714080902127MainActivity.java
- students/soft1714080902127/实验5/main/res/layout/soft_1714080902127_mainactivity.xml
- students/soft1714080902127/实验5/main/res/layout/title.xml
使用文件存储，存储方式是内部存储
在EditText中输入数据，并保存
退出Activity重新打开
从文件中读取数据
> #5 #382 提交实验五代码

- students/soft1714080902302/Activity_food.java
- students/soft1714080902302/activity_food.xml
> #5 #302 第五次实验

- students/soft1714080902309/实验五/app/src/main/AndroidManifest.xml
- students/soft1714080902309/实验五/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902309/Soft1714080902309Activity.java
- students/soft1714080902309/实验五/app/src/main/res/layout/soft_1714080902309_activity.xml
- students/soft1714080902309/实验五/app/src/main/res/values/strings.xml
老师，第二个文件我应该备注“实现用户存储数据到手机和用户从文件中读取数据”，我备注错了，但是已经push了，改不了备注好像。在这里和您说明一下。还有附上程序存储的文件截图
> #5  提交实验五代码

- students/soft1714080902240/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902240/Soft1714080902240Activity3.java
- students/soft1714080902240/app/src/main/res/layout/activity_soft17140809022402.xml
- students/soft1714080902240/app/src/main/res/layout/activity_soft17140809022403.xml
> #5 #YZT6 第五次实验

- students/Soft1714080902335/shiyan4/AndroidManifest.xml
- students/Soft1714080902335/shiyan4/SecondActivity.java
- students/Soft1714080902335/shiyan4/Soft1714080902335Activity.java
- students/Soft1714080902335/shiyan4/ThirdActivity.java
- students/Soft1714080902335/shiyan4/activity_second.xml
- students/Soft1714080902335/shiyan4/activity_soft1714080902335.xml
- students/Soft1714080902335/shiyan4/activity_third.xml
- students/Soft1714080902335/shiyan4/strings.xml
1.创建了简单的按钮操作，在界面上可以显示出两个检索功能
2.按下检索功能键可以进入对应的界面功能，后面的具体功能还待开发。
3本实验仅是界面布局以及按钮操作的开发，后续将有完善。
> #4 #942 第四次实验

- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/dao/TaskDao.java
- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/dao/TaskDatabaseHelper.java
- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/listview/HomeListAdapter.java
- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/model/Task.java
- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/presenter/TaskService.java
- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902223/DetailActivity.java
- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902223/EditActivity.java
- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902223/HomeActivity.java
- students/soft1714080902223/app/src/main/res/layout/activity_detail.xml
- students/soft1714080902223/app/src/main/res/layout/activity_edit.xml
- students/soft1714080902223/app/src/main/res/layout/activity_home.xml
- students/soft1714080902223/app/src/main/res/layout/list_item.xml
- students/soft1714080902223/app/src/main/res/values/colors.xml
1.使用sqlite3数据库，并编写dao层代码
2.根据数据表编写model
3.主页为每个listitem设置视图，并把数据显示到listView中
4.编辑页将输入的数据保存到数据库，传参并跳转到详情页
5.显示详情页
6.主页数据更新，按最新更新的顺序排序
> #5 #534 第五次实验

- students/soft1714080902336/shiyan5/AddActivity.java
- students/soft1714080902336/shiyan5/Soft1714080902336Activity.java
- students/soft1714080902336/shiyan5/activity_add.xml
- students/soft1714080902336/shiyan5/activity_soft1714080902336.xml
此次实验我在第四次实验基础下做如下改动：
1.主页面：多增加了一个按钮来跳转到添加好友的页面，点击之后将会跳到添加好友的页面
2.在添加好友的页面可以输入你要添加的好友的姓名，性别和等级，点击保存查询的按钮可以将该查询保存起来
3.点击读取查询的按钮可以查看想要添加的好友的查询
> #5 #275 第五次实验

- students/soft1714080902339/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902339/SecondActivity.java
- students/soft1714080902339/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902339/WriteActivity.java
- students/soft1714080902339/app/src/main/res/layout/activity_write.xml
- students/soft1714080902339/app/src/main/res/layout/second_activity.xml
1.在第二个页面添加一个按钮：记录生词
2.点击按钮后跳转到write页面，填写生词，做记录
3.填写生词，点击保存按钮
4.下次打开时，在安卓虚拟机里可以找到date.text文件，显示如下
达到了预期效果
> #5 #290 提交实验五代码文件

- students/soft1714080902203/实验五/My Application/app/src/main/AndroidManifest.xml
- students/soft1714080902203/实验五/My Application/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902203/Soft1714080902203Activity2.java
- students/soft1714080902203/实验五/My Application/app/src/main/res/layout/soft_1714080902203_activity2.xml
- students/soft1714080902203/实验五/My Application/app/src/main/res/values/strings.xml
> #5 第五次实验代码 #262

- students/soft1714080902205/app/src/main/AndroidManifest.xml
- students/soft1714080902205/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902205/NewActivity.java
- students/soft1714080902205/app/src/main/res/layout/activity_new.xml
文件存储：内部
1.点击Soft1714080902205Activity.java页面的新建按钮，进入新建书籍页面NewActivity.java：
2.点击EditText控件进行输入：
3.点击保存按钮将输入的文本数据存储到名为“MyBoot.txt”文件中：
4.点击查看按钮提取存储的数据并显示：
> #5 #342 提交实验五

- students/soft1714080902101/app/src/main/java/edu/hzuapps/androidlabs/soft17140080902101/ChattingActivity.java
- students/soft1714080902101/app/src/main/res/layout/activity_chatting.xml
> #5 #388 提交实验五代码

- students/soft1714080902126/app/src/main/AndroidManifest.xml
- students/soft1714080902126/app/src/main/java/edu/hzuapps/androidlabs/soft171408902126/tzactivity.java
- students/soft1714080902126/app/src/main/res/layout/activity_tzactivity.xml
> #5 提交第5次实验

- students/soft1714080902116/MyApplicationfour/app/src/main/AndroidManifest.xml
- students/soft1714080902116/MyApplicationfour/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902116/Main2ActivitySoft1714080902116.java
- students/soft1714080902116/MyApplicationfour/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902116/MainActivitySoft1714080902116.java
- students/soft1714080902116/MyApplicationfour/app/src/main/res/layout/activity_main2_activity_soft1714080902116.xml
读取用户喜欢的动漫人物并且保存动漫人物的名字，下次可以加入该动漫人物的图片
> #5 #1135 提交第五次实验

- students/Soft1714080902239/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902239/Second_A.java
- students/Soft1714080902239/app/src/main/res/layout/soft_1714080902239_activity/activity_second.xml
> #5 #1286#实验五

- students/soft1714080902131/experiment5/AndroidManifest.xml
- students/soft1714080902131/experiment5/java/edu/hzuapps/androidlabs/soft1714080902131/Soft1714080902131EditActivity.java
- students/soft1714080902131/experiment5/res/layout/activity_soft1714080902131_edit.xml
采用内部存储
1.点击加号进入编辑事务界面
2.编辑事务，保存事务
> #5 #310 提交实验5代码

- students/soft1714080902204/Soft1714080902204Activity_third.java
- students/soft1714080902204/activity_soft1714080902204_second.xml
- students/soft1714080902204/activity_soft1714080902204_third.xml
- students/soft1714080902204/strings.xml
> #5#337提交实验五代码

- students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com17140809011MainActivity.java
- students/com171408901141/app/src/main/res/layout/activity_main.xml
- students/com171408901141/app/src/main/res/menu/navigation.xml
- students/com171408901141/app/src/main/res/values/strings.xml
> #2 #1333 提交实验2代码

- students/soft1714080902331/AndroidManifest.xml
- students/soft1714080902331/Soft1714080902331Activity2.java
- students/soft1714080902331/soft_1714080902331_activity2.xml
- students/soft1714080902331/strings.xml
做的是内容二，通过一个按钮，直接从网上获取心情图片，并在一个ImageView中使用。
> #6 提交实验六代码

- students/com171408901141/app/src/main/AndroidManifest.xml
- students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141ActivityCollector.java
- students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141BaseActivity.java
- students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141DialogActivity.java
- students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141MainActivity.java
- students/com171408901141/app/src/main/res/layout/activity_dialog.xml
- students/com171408901141/app/src/main/res/layout/activity_main.xml
- students/com171408901141/app/src/main/res/menu/navigation.xml
- students/com171408901141/app/src/main/res/values/strings.xml
- students/com171408901141/app/src/main/res/values/styles.xml
图片资源引用前：
图片资源引用后：
点击退出键时，跳转到DialogActivity页面：
继续惭愧地补交作业中
> #3 #1333 提交实验3代码

- students/soft1714080902232/app/src/main/AndroidManifest.xml
- students/soft1714080902232/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902232/Soft1714080902232Activity_MyImageView.java
- students/soft1714080902232/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902232/Soft1714080902232Activity_Web.java
- students/soft1714080902232/app/src/main/res/layout/soft_1714080902232_activity_web.xml
我选做是实验内容二
1.app主界面如下：
2.点击游戏帮助按钮，跳转如下：
3.点击按钮获取获取游戏帮助：
> #6 #533 第六次实验

- students/com1714080901129/app/src/main/AndroidManifest.xml
- students/com1714080901129/app/src/main/java/edu/hzuapps/androidlabs/com1714080901129/Com1714080901129Activity.java
- students/com1714080901129/app/src/main/java/edu/hzuapps/androidlabs/com1714080901129/Lab5Activity.java
- students/com1714080901129/app/src/main/res/drawable/bt_shape.xml
- students/com1714080901129/app/src/main/res/drawable/ed_text_shape.xml
- students/com1714080901129/app/src/main/res/layout/activity_lab5.xml
> #5 #415 第5次实验

- students/com171408901141/app/src/main/AndroidManifest.xml
- students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141DialogActivity.java
- students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141MainActivity.java
以下是点击在MainActivity中点击返回键之后的截屏
实在抱歉，几乎每次都是补交。。。
> #4 #1333 提交实验4代码

- students/Soft1714080902335/shiyan5/AndroidManifest.xml
- students/Soft1714080902335/shiyan5/Soft1714080902335Activity.java
- students/Soft1714080902335/shiyan5/activity_soft1714080902335.xml
- students/Soft1714080902335/shiyan5/fifth.java
- students/Soft1714080902335/shiyan5/fifth.xml
> #5 #942   第五次实验

- students/soft1714080902336/shiyan6/AndroidManifest.xml
- students/soft1714080902336/shiyan6/Tv_Test01_Activity.java
- students/soft1714080902336/shiyan6/activity_tv_test01.xml
这次实验我在实验五的基础上多增加了一个Activity，来表示影视库中的第一道题
这次我采用的是第二种方式，通过在Activity中增加函数在网上下载图片，通过点击“获取图片”按钮可显示到页面中
（1）进入影视库时的截图：
（2）点击“获取图片”按钮前的页面截图：
（3）点击“获取图片”按钮后的页面截图：
> #6 #275 第六次实验

- students/soft1714080902223/app/src/main/AndroidManifest.xml
- students/soft1714080902223/app/src/main/info.json
- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/dao/TaskDao.java
- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/model/Task.java
- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/presenter/JsonService.java
- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902223/DetailActivity.java
- students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902223/HomeActivity.java
- students/soft1714080902223/app/src/main/res/layout/activity_home.xml
- students/soft1714080902223/app/src/main/res/layout/list_item.xml
1.json文件
2.建立http连接并抓取json，在主页展示
3.新增详情页跳转功能
（吐槽：我的选题去网上获取json根本多此一举！好吧作业，要冷静）
> #6 #534 实验六作业

- students/soft1714080902219/app/src/main/AndroidManifest.xml
- students/soft1714080902219/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902219/Soft1714080902219Activity3.java
- students/soft1714080902219/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902219/Soft1714080902219Fragment2.java
- students/soft1714080902219/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902219/Soft1714080902219MyAdapter.java
- students/soft1714080902219/app/src/main/res/layout/soft_1714080902219_fragment2.xml
- students/soft1714080902219/app/src/main/res/layout/soft_1714080902219_item_xml.xml
JSON文件的url:
https://raw.githubusercontent.com/wanshanghong/liulangzhe/master/myjson.json
通过设置网络权限，访问url,将数据显示到activity中的一个fragment中的ListView（要自定义一个适配器Soft1714080902219MyAdapter）
运行截图：
> #6 #324 第6次实验

- students/Soft1714080902118/Json/get_data.json
- students/Soft1714080902118/实验6/app/src/main/AndroidManifest.xml
- students/Soft1714080902118/实验6/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902118/App.java
- students/Soft1714080902118/实验6/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902118/Soft1714080902118MainActivity.java
> #6 #359 提交实验六代码

- students/soft1714080902101/app/src/main/AndroidManifest.xml
- students/soft1714080902101/app/src/main/java/edu/hzuapps/androidlabs/soft17140080902101/DownloadTask.java
- students/soft1714080902101/app/src/main/java/edu/hzuapps/androidlabs/soft17140080902101/ReadActivity.java
- students/soft1714080902101/app/src/main/res/layout/activity_read.xml
> #6 #388 提交实验六代码

- students/soft1714080902311/实验六/SecondActivity.java
- students/soft1714080902311/实验六/activity_second.xml
1.点击获取配图通过网络获取图片
2.点击图片存储到sd卡
3.在SD卡中查看图片
> #6 #302 提交实验六代码 下载图片

- students/soft1707080412124/app/src/main/AndroidManifest.xml
- students/soft1707080412124/app/src/main/java/edu/hzuapps/androidlabs/soft1707080412124/ThirdActivity.java
- students/soft1707080412124/app/src/main/res/layout/activity_third.xml
> #6#299提交实验六代码

- students/soft1714080902339/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902339/SecondActivity.java
- students/soft1714080902339/app/src/main/res/AndroidManifest.xml
- students/soft1714080902339/app/src/main/res/layout/second_activity.xml
老师好，我在实验6中按照要求添加功能如下：
1.加入权限访问请求
2.新增一个“获取印象单词图片”按钮，可从网络上获取到一张单词图片，并显示出来
3.点击图片时，会保存到本地test文件中
4.在本地中查看已保存的图片
> #6 #290 提交实验6代码文件

- students/soft1714080902133/app/src/main/AndroidManifest.xml
- students/soft1714080902133/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902133/Soft1714080902133QueryActivity.java
- students/soft1714080902133/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902133/javabean/Soft1714080902133Dor.java
- students/soft1714080902133/app/src/main/res/layout/soft_1714080902133_queryactivity.xml
- students/soft1714080902133/app/src/main/res/values/strings.xml
- students/soft1714080902133/data.json
> #6 #238 提交实验6代码

- students/Soft1714080902328/SaveImageViewActivity.java
- students/Soft1714080902328/activity_save_image_view.xml
- students/Soft1714080902328/activity_user.xml
选题2
大致和上次提交的内容一样，上次的实验就已经做到了获取网络上图片，并使用，对整体的界面进行了优化，自学增加了上下滑轮，并额外设置了一个按钮.xml文件用来调试app中所有的按钮样式。给我的感觉，和前端很像，app里的按钮图片等等控件都可以通过设置一个和前端里相同的css来设置。
> #6 #zweixiao 第六次实验

- students/soft1714080902214/userinfo.xml
- students/soft1714080902214/第六次实验/Soft1714080902214Activity5.java
- students/soft1714080902214/第六次实验/User.java
- students/soft1714080902214/第六次实验/UserService.java
在主界面添加“星星球排行榜”按钮。通过网络编程访问数据文件，解析xml后在activity中使用setText设置文本内容，显示在对应位置
> #6 第六次实验 解析XML

- students/soft1714080902433/six/app/src/main/AndroidManifest.xml
- students/soft1714080902433/six/app/src/main/java/com/example/lenovo/soft1714080902433/Activity02.java
- students/soft1714080902433/six/app/src/main/java/com/example/lenovo/soft1714080902433/Activity03.java
- students/soft1714080902433/six/app/src/main/java/com/example/lenovo/soft1714080902433/MainActivity.java
- students/soft1714080902433/six/app/src/main/res/layout/activity02.xml
- students/soft1714080902433/six/app/src/main/res/layout/activity03.xml
- students/soft1714080902433/six/app/src/main/res/layout/activity_main.xml
- students/soft1714080902433/six/app/src/main/res/values/colors.xml
- students/soft1714080902433/six/app/src/main/res/values/strings.xml
- students/soft1714080902433/six/app/src/main/res/values/styles.xml
> #6 第6次实验 HttpURLConnection下载图片

- students/soft1714080902131/experiment6/AndroidManifest.xml
- students/soft1714080902131/experiment6/java/edu/hzuapps/androidlabs/soft1714080902131/Soft1714080902131EditActivity.java
- students/soft1714080902131/experiment6/res/layout/activity_soft1714080902131_edit.xml
> #6 #310 提交实验六代码

- students/soft1714080902436/app/src/main/AndroidManifest.xml
- students/soft1714080902436/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902436/Soft1714080902436Activity.java
- students/soft1714080902436/app/src/main/res/layout/soft_1714080902436_activity.xml
- students/soft1714080902436/app/src/main/res/values/strings.xml
> #6 #520 第六次实验 HttpURLConnection下载图片

- students/soft1714080902331/AndroidManifest.xml
- students/soft1714080902331/Soft1714080902331Activity.java
- students/soft1714080902331/Soft1714080902331Activity4.java
- students/soft1714080902331/file_paths.xml
- students/soft1714080902331/soft_1714080902331_activity.xml
- students/soft1714080902331/soft_1714080902331_activity4.xml
调用了手机的照相和相册，可对得到的图片进行修剪，蓝牙感觉这个不需要用到，就没做。
> #7 提交实验七代码

- students/com1714080901108/Com1714080901108Activity.java
- students/com1714080901108/app/src/main/AndroidManifest.xml
- students/com1714080901108/app/src/main/assets/Information.json
- students/com1714080901108/app/src/main/java/edu/hzuapps/androidlabs/com1714080901108/Json2Activity.java
- students/com1714080901108/app/src/main/java/edu/hzuapps/androidlabs/com1714080901108/Main3Activity.java
- students/com1714080901108/app/src/main/res/layout/activity_json2.xml
- students/com1714080901108/app/src/main/res/layout/content_main3.xml
- students/com1714080901108/app/src/main/res/values/styles.xml
> #6 第六次实验代码

- students/soft1714080902315/basketball/app/src/main/AndroidManifest.xml
- students/soft1714080902315/basketball/app/src/main/java/com/example/administrator/basketball/pictureActivity.java
- students/soft1714080902315/basketball/app/src/main/res/layout/activity_picture.xml
> #6 #1714080902315 第六次实验

- students/soft1714080902209/HR管理系统/app/src/main/AndroidManifest.xml
- students/soft1714080902209/HR管理系统/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902209_AddInfo.java
- students/soft1714080902209/HR管理系统/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902209_JSON.java
- students/soft1714080902209/HR管理系统/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902209_Login.java
- students/soft1714080902209/HR管理系统/app/src/main/res/JSON/candidate.json
> #6 #339 Exp6_HRMS_JSON

- students/soft1707080412124/app/src/main/AndroidManifest.xml
- students/soft1707080412124/app/src/main/java/edu/hzuapps/androidlabs/soft1707080412124/ConnectionUtil.java
- students/soft1707080412124/app/src/main/java/edu/hzuapps/androidlabs/soft1707080412124/Soft1707080412124Activity.java
本次实验选择控制和检测网络功能
将网络全部关闭后打开APP
点击设置，跳转到网络设置界面，即可控制网络
> #7#299 提交实验7代码  检测网络并控制

- students/soft1714080902133/app/src/main/AndroidManifest.xml
- students/soft1714080902133/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902133/Soft1714080902133UserActivity.java
- students/soft1714080902133/app/src/main/res/layout/soft_1714080902133_useractivity.xml
- students/soft1714080902133/app/src/main/res/layout/user_context.xml
- students/soft1714080902133/app/src/main/res/values/strings.xml
- students/soft1714080902133/app/src/main/res/xml/file_paths.xml
首页
点击个人中心
点击头像选择获取图片的方式
选择拍照（图片是拍我的github的本地库）
选择相册
> #7 #238 提交实验7代码 拍照或者选取相册图片并显示作为头像

- students/soft1714080902219/app/src/main/AndroidManifest.xml
- students/soft1714080902219/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902219/PictureUtils.java
- students/soft1714080902219/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902219/Soft1714080902219Activity3.java
- students/soft1714080902219/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902219/Soft1714080902219Fragment3.java
- students/soft1714080902219/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902219/Soft1714080902219TakephotoActivity.java
- students/soft1714080902219/app/src/main/res/layout/soft_1714080902219_fragment3.xml
- students/soft1714080902219/app/src/main/res/layout/soft_1714080902219_takephoto_activity.xml
- students/soft1714080902219/app/src/main/res/xml/file_paths.xml
> #7 #324 第7次实验

- students/soft1714080902407/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902407/ConnectionUtil.java
- students/soft1714080902407/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902407/Soft1714080902407Activity.java
控制和检测网络：聊天室必须联网，打开app，若检测到没有网络，就会提示去设置网络。
> #7 #284 第7次实验

- students/soft1714080902323/AndroidManifest.xml
- students/soft1714080902323/Soft1714080902323Activity6.java
- students/soft1714080902323/soft_1714080902323_activity6.xml
选题：相机编程-上传学生照片
题号：#281
通过照相上传学生的照片或则通过图片上传学生照片
界面截图如下：
> #7 提交第七次实验代码

- students/com1714080901123/app/src/main/AndroidManifest.xml
- students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123ActivityAmiibo.java
- students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123ActivityAmiiboSharePhoto.java
- students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123ClassDrawableID.java
- students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123FragmentAmiibo.java
- students/com1714080901123/app/src/main/res/drawable/bg_border.xml
- students/com1714080901123/app/src/main/res/drawable/shape_amiibo_share_button.xml
- students/com1714080901123/app/src/main/res/layout/activity_com1714080901123_amiibo.xml
- students/com1714080901123/app/src/main/res/layout/activity_com1714080901123_amiibo_share_photo.xml
- students/com1714080901123/app/src/main/res/values/colors.xml
- students/com1714080901123/app/src/main/res/values/dimens.xml
- students/com1714080901123/app/src/main/res/values/styles.xml
- students/com1714080901123/app/src/main/res/xml/file_paths.xml
这次更新了 使用相机拍照 和 选择相册照片 的功能。
在每个amiibo的资料界面，可以点击分享照片按钮进入分享界面，可选择立即拍照或选择相册照片：
> #7 #269 提交实验七代码

- students/soft1509081602625/app/src/main/AndroidManifest.xml
- students/soft1509081602625/app/src/main/java/soft1509081602625/androidlabs/hzuapps/edu/soft1509081602625activity/CarinfoActivity.java
- students/soft1509081602625/app/src/main/java/soft1509081602625/androidlabs/hzuapps/edu/soft1509081602625activity/ConnectionUtil.java
- students/soft1509081602625/app/src/main/java/soft1509081602625/androidlabs/hzuapps/edu/soft1509081602625activity/Soft1509081602625Activity.java
> #7 SunJiashun 实验七控制和检测网络

- students/soft1714080902121/app/src/main/RateList.json
- students/soft1714080902121/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902121/exratecalculator/Soft1714080902121MainActivity.java
- students/soft1714080902121/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902121/exratecalculator/Soft1714080902121RateListActivity.java
- students/soft1714080902121/app/src/main/res/values/strings.xml
> #7 #372 提交实验7代码 使用BroadReceiver监听网络状态

- students/soft1714080902311/实验七/AndroidManifest.xml
- students/soft1714080902311/实验七/ConnectionUtil.java
- students/soft1714080902311/实验七/Soft1714080902311Activity.java
> #7 #302提交实验七代码

- students/soft1714080902216/edu/hzuapps/androidlabs/soft1714080902216/Soft1714080902216LocationActivity.java
- students/soft1714080902216/edu/hzuapps/androidlabs/soft1714080902216/Soft1714080902216MainActivity.java
- students/soft1714080902216/layout/activity_main.xml
- students/soft1714080902216/layout/activity_soft1714080902216_location.xml
> #7 #249 获取用户位置信息方便得知当地时区时间

- students/soft1714080902202/第七次实验/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902202/Soft1714080902202MainPage.java
- students/soft1714080902202/第七次实验/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902202/Soft1714080902202locate.java
- students/soft1714080902202/第七次实验/app/src/main/res/layout/activity_main.xml
- students/soft1714080902202/第七次实验/app/src/main/res/layout/activity_soft1714080902202locate.xml
在主页
点击查看‘’当前位置按钮‘’即可查看用户经纬度位置信息
> #7 #256 第七次实验

- students/soft1714080902125/AndroidManifest.xml
- students/soft1714080902125/java/edu/hzuapps/androidlabs/soft1714080902125/Soft1714080902125Activity.java
检查网络设置：
未连接到网络时打开app：
点击设置跳转到网络设置：
> #7 #328 提交实验七代码

- students/soft1714080902214/第六次实验/ShakeListener.java
- students/soft1714080902214/第六次实验/Soft1714080902214Activity6.java
- students/soft1714080902214/第六次实验/Utils.java
在主页面增加“找好友”功能，进入Activity6，仿微信摇一摇，寻找同一时间摇手机的养鸡好友。在AndroidManifest中添加震动和加速传感器的权限。
Units负责完成动画播放、声音播放，可在Activity6中直接调用。
在ShakeListener中检测手机是否支持加速传感器，再通过加速感应器获得数据变化，计算速度，若达到指定值则发出提示。
在Activity6中检测到速度达到指定值，播放声音、执行震动、发出提示。完成后再次开始检测加速传感器的值，等待下次摇一摇。
> #7 #319 第七次实验

- students/soft1714080902226/app/src/main/AndroidManifest.xml
- students/soft1714080902226/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902226activity/ConnectionUtil.java
- students/soft1714080902226/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902226activity/Soft1714080902226Activity2.java
> #7 #munxuny 第七次实验

- students/soft1714080902127/实验7/main/AndroidManifest.xml
- students/soft1714080902127/实验7/main/java/edu/hzuapps/androidlabs/cameraalbumtest/MainActivity.java
- students/soft1714080902127/实验7/main/res/layout/activity_main.xml
> #7 #382提交实验7代码

- students/soft1714080902141/app/src/main/AndroidManifest.xml
- students/soft1714080902141/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902141/Main3Activity.java
- students/soft1714080902141/app/src/main/res/layout/activity_main3.xml
为游戏界面设置背景图片，可选择默认图片，也可通过输入图片地址获取网络图片
> #6 #1059 实验6

- students/soft1714080902339/app/src/main/AndroidManifest.xml
- students/soft1714080902339/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902339/Soft1714080902339Activity.java
老师好，我选择实现控制和检测网络功能
1 安卓虚拟机中先断开网络，我才用开启飞行模式：
2 接着运行我的项目，在无网络条件下，在我的Activity中会提示没有网络，让用户选择设置
> #7 #290 提交实验7代码文件

- students/com1714080901131/app/src/main/AndroidManifest.xml
- students/com1714080901131/app/src/main/java/edu/hzuapps/androidlabs/com1714080901131/Com1714080901131Activity.java
- students/com1714080901131/app/src/main/java/edu/hzuapps/androidlabs/com1714080901131/Com1714080901131Activity2.java
- students/com1714080901131/app/src/main/res/layout/com_1714080901131_activity2.xml
- students/com1714080901131/app/src/main/res/values/strings.xml
为备忘录实现相机功能
（1）点击新建
（2）添加标题和内容，并点击拍照按钮
（3）出现如下界面 拍照并确定
（4）结果如图所示，之后我们可以点击保存将文字和图片一起保存进入数据库中。
> #7 #1003 提交实验7代码

- students/soft1714080902318/app/src/main/AndroidManifest.xml
- students/soft1714080902318/app/src/main/java/com/example/myapplication/myapplication02/FourthActivity.java
- students/soft1714080902318/app/src/main/java/com/example/myapplication/myapplication02/SecondActivity.java
- students/soft1714080902318/app/src/main/java/com/example/myapplication/myapplication02/Soft1714080902318MainActivity.java
- students/soft1714080902318/app/src/main/java/com/example/myapplication/myapplication02/ThirdActivity.java
- students/soft1714080902318/app/src/main/res/layout/activity_fourth.xml
- students/soft1714080902318/app/src/main/res/layout/activity_second.xml
- students/soft1714080902318/app/src/main/res/layout/activity_soft1714080902318_main.xml
- students/soft1714080902318/app/src/main/res/layout/activity_third.xml
暂时移除了通往第三个Activity的按钮，后面的实验会再用到。
> #5 #1052 提交实验五代码+补交实验四代码到自己的库内

- students/Soft1714080902118/实验7/app/src/main/AndroidManifest.xml
- students/Soft1714080902118/实验7/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902118/Soft1714080902118ShowActivity.java
- students/Soft1714080902118/实验7/app/src/main/res/layout/soft_1714080902118_showactivity.xml
> #7 #359 提交第七次代码

- students/soft1714080902427/Soft1714080902427test7Application/app/src/main/AndroidManifest.xml
- students/soft1714080902427/Soft1714080902427test7Application/app/src/main/java/com/example/soft1714080902427test7application/MainActivity.java
- students/soft1714080902427/Soft1714080902427test7Application/app/src/main/res/layout/activity_main.xml
> #7 #469 第7次实验

- students/soft1714080902413/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902413/wuziqi/Soft1714080902413Activity.java
- students/soft1714080902413/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902413/wuziqi/Soft1714080902413Activity5.java
- students/soft1714080902413/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902413/wuziqi/Soft1714080902413record.java
- students/soft1714080902413/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902413/wuziqi/Soft1714080902413rule.java
- students/soft1714080902413/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902413/wuziqi/Soft1714080902413startgame.java
- students/soft1714080902413/app/src/main/res/layout/activity_soft17140809024132.xml
- students/soft1714080902413/app/src/main/res/layout/activity_soft17140809024133.xml
- students/soft1714080902413/app/src/main/res/layout/activity_soft17140809024134.xml
> #7 #634 第7次实验

- students/soft1714080902131/experiment7/AndroidManifest.xml
- students/soft1714080902131/experiment7/java/edu/hzuapps/androidlabs/soft1714080902131/Soft1714080902131MainActivity.java
选择（2）控制和检测网络，使用BroadcastReceiver监听网络状况并跳转设置网络
1、正常联网状态下
2、断开网络时
3、设置网络
> #7 #310 提交实验7代码

- students/soft1714080902227/#7/java/edu/androidlabs/soft1714080902227/ImageAdapter.java
- students/soft1714080902227/#7/java/edu/androidlabs/soft1714080902227/ImagePreviewActivity.java
- students/soft1714080902227/#7/java/edu/androidlabs/soft1714080902227/Soft1714080902227Activity.java
- students/soft1714080902227/#7/java/edu/androidlabs/soft1714080902227/Soft1714080902227Activity2.java
- students/soft1714080902227/#7/java/edu/androidlabs/soft1714080902227/Soft1714080902227Activity3.java
- students/soft1714080902227/#7/java/edu/androidlabs/soft1714080902227/Soft1714080902227Fragment.java
- students/soft1714080902227/#7/java/edu/androidlabs/soft1714080902227/Soft1714080902227Fragment2.java
- students/soft1714080902227/#7/java/edu/androidlabs/soft1714080902227/Soft1714080902227Fragment3.java
- students/soft1714080902227/#7/java/edu/androidlabs/soft1714080902227/Soft1714080902227Fragment4.java
- students/soft1714080902227/#7/res/layout/activity_image_preview.xml
- students/soft1714080902227/#7/res/layout/activity_main.xml
- students/soft1714080902227/#7/res/layout/activity_main2.xml
- students/soft1714080902227/#7/res/layout/activity_main3.xml
- students/soft1714080902227/#7/res/layout/album.xml
- students/soft1714080902227/#7/res/layout/dialog_item.xml
- students/soft1714080902227/#7/res/layout/find.xml
- students/soft1714080902227/#7/res/layout/image_item_layout.xml
- students/soft1714080902227/#7/res/layout/item.xml
- students/soft1714080902227/#7/res/layout/mediaprovidertest.xml
- students/soft1714080902227/#7/res/layout/photo.xml
- students/soft1714080902227/#7/res/layout/photoshow.xml
- students/soft1714080902227/#7/res/layout/search.xml
- students/soft1714080902227/#7/res/layout/title.xml
1.加入打开相机的按钮
2.关键代码：
public void onClick(View v) {
if (ContextCompat.checkSelfPermission(getContext(), Manifest.permission.CAMERA) == PackageManager.PERMISSION_DENIED) {
requestPermissions(new String[]{Manifest.permission.CAMERA}, 1);
}else {
Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
intent.putExtra(MediaStore.EXTRA_OUTPUT,false);
startActivityForResult(intent, 1);
}
}
> #7 #325 第七次实验

- students/com1714080901129/app/src/main/AndroidManifest.xml
- students/com1714080901129/app/src/main/java/edu/hzuapps/androidlabs/com1714080901129/CameraActivity.java
- students/com1714080901129/app/src/main/java/edu/hzuapps/androidlabs/com1714080901129/Com1714080901129Activity.java
- students/com1714080901129/app/src/main/res/layout/activity_camera_activty.xml
- students/com1714080901129/app/src/main/res/xml/filepath.xml
> #7 #415 第7次实验

- students/soft1714080902437/test7/SignActivity.java
- students/soft1714080902437/test7/activity_sign.xml
> #7 #293 摇一摇实现签到

- students/soft1714080902330/test7/main/AndroidManifest.xml
- students/soft1714080902330/test7/main/java/com/edu/hzuapps/abdroidlads/soft1714080902330/MusicActivity.java
- students/soft1714080902330/test7/main/res/layout/iron.xml
- students/soft1714080902330/test7/main/res/layout/music_activity.xml
- students/soft1714080902330/test7/main/res/painting_main.xml
> #7 #297 实验七

- students/soft1714080902135/app/src/main/java/edu/hzuapps/androidlabs/lsm/MainActivity.java
- students/soft1714080902135/app/src/main/res/layout/activity_main.xml
> #6 #596提交实验六代码并修改相关界面

- students/soft1714080902434/java/edu/hzuapps/androidlabs/soft1714080902434/EntryActivity.java
- students/soft1714080902434/res/layout/activity_entry.xml
老师，我提交文件时文件名错写成了第五次实验，但这是第六次实验，还请不要在意这些细节，求过，谢谢老师
> #6 #623 第六次实验 使用HttpURLConnect浏览图片

- students/soft1714080902101/app/src/main/AndroidManifest.xml
- students/soft1714080902101/app/src/main/java/edu/hzuapps/androidlabs/soft17140080902101/NetWorkStateReceiver.java
- students/soft1714080902101/app/src/main/java/edu/hzuapps/androidlabs/soft17140080902101/Soft1714080902101Activity.java
> #7 #388 第七次实验

- students/soft1714080902203/shiyan7/MyApplication4/app/src/main/AndroidManifest.xml
- students/soft1714080902203/shiyan7/MyApplication4/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902203/Soft1714080902203Activity2.java
- students/soft1714080902203/shiyan7/MyApplication4/app/src/main/res/layout/soft_1714080902203_activity2.xml
- students/soft1714080902203/shiyan7/MyApplication4/app/src/main/res/values/strings.xml
- students/soft1714080902203/shiyan7/MyApplication4/app/src/main/res/xml/file_paths.xml
- students/soft1714080902203/shiyan7/MyApplication4/app/src/main/res/xml/network_security_config.xml
这次做的是实现拍照和显示
点击跳转后会出现可以拍照的页面
点击相册选择可以把选择后的照片显示在页面上
由于建好的apk安装后一直会出现闪退，找不到原因和错误，所以现在才搞定！！！
> #7 #262提交实验7代码 拍照页面

- students/soft1714080902240/app/src/main/AndroidManifest.xml
- students/soft1714080902240/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902240/ConnectionUtil.java
- students/soft1714080902240/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902240/Soft1714080902240Activity.java
- students/soft1714080902240/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902240/Soft1714080902240Activity4.java
- students/soft1714080902240/app/src/main/res/layout/activity_soft17140809022402.xml
- students/soft1714080902240/app/src/main/res/layout/soft_1714080902240_activity.xml
在保存单词操作前进行网络检测
若没联网则提示要联网
若联网了则正常操作
> #7 #536 提交实验7

- students/soft1714080902238/Android Final/AndroidManifest.xml
- students/soft1714080902238/Android Final/CarActivity.java
- students/soft1714080902238/Android Final/DisplayActivity.java
- students/soft1714080902238/Android Final/DownLoad.java
- students/soft1714080902238/Android Final/DownPicActivity.java
- students/soft1714080902238/Android Final/ItemActivity.java
- students/soft1714080902238/Android Final/ShoppingActivity.java
- students/soft1714080902238/Android Final/activity_car.xml
- students/soft1714080902238/Android Final/activity_display.xml
- students/soft1714080902238/Android Final/activity_down_pic.xml
- students/soft1714080902238/Android Final/activity_item.xml
- students/soft1714080902238/Android Final/activity_shopping.xml
1、开头检查网络连接，提醒用户网络是否正常。
2、点击图片快速加入购物车
3、可放大物品图片并且可选择下载到手机内存
> #8 #252  实验8 综合编程代码提交

- students/soft1714080902321/app/src/main/AndroidManifest.xml
- students/soft1714080902321/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902321activity/Soft1714080902321Activity.java
- students/soft1714080902321/app/src/main/res/layout/activity_1714080902321.xml
> #6 #286 第六次实验

- students/soft1714080902318/app/src/main/AndroidManifest.xml
- students/soft1714080902318/app/src/main/java/com/example/myapplication/myapplication02/FifthActivity.java
在主菜单上新增一个按钮通往实现摇一摇功能的activity，通过该功能来实现新角色卡池的抽取。
选题号：611
> #7 #611 提交实验七代码

- students/soft1714080902319/shiyan7/AndroidManifest.xml
- students/soft1714080902319/shiyan7/MainActivity.java
- students/soft1714080902319/shiyan7/activity_main.xml
- students/soft1714080902319/shiyan7/activity_main_2.xml
- students/soft1714080902319/shiyan7/main2.java
> #7 #277 提交实验7

- students/soft1714080902322/app/src/main/AndroidManifest.xml
- students/soft1714080902322/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902322/CameraActivity.java
- students/soft1714080902322/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902322/DownloadActivity.java
- students/soft1714080902322/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902322/PreviewActivity.java
- students/soft1714080902322/app/src/main/res/layout/activity_camera2.xml
- students/soft1714080902322/app/src/main/res/layout/activity_download.xml
> #6 #282 实验六(选做二)

- students/soft1714080902439/test7/Soft1714080902439PresentActivity.java
- students/soft1714080902439/test7/soft_1714080902439_present_activity.xml
> #7 #294 完善补充实验七代码

- students/soft1714080902321/app/src/main/AndroidManifest.xml
- students/soft1714080902321/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902321activity/SharkActivity.java
- students/soft1714080902321/app/src/main/res/layout/activity_shark.xml
> #7 #286 第七次实验

- students/soft1714080902135/app/src/main/AndroidManifest.xml
- students/soft1714080902135/app/src/main/java/edu/hzuapps/androidlabs/lsm/MainActivity.java
- students/soft1714080902135/app/src/main/res/layout/activity_main.xml
> #7 #596  提交实验7代码

- students/com1714080901237/app/src/main/AndroidManifest.xml
- students/com1714080901237/app/src/main/java/com/example/eduhuzappfuyouapp/Com1714080901237Activity.java
- students/com1714080901237/app/src/main/java/com/example/eduhuzappfuyouapp/Com1714080901237Activity02.java
- students/com1714080901237/app/src/main/java/com/example/eduhuzappfuyouapp/Com1714080901237Activity03.java
- students/com1714080901237/app/src/main/java/com/example/eduhuzappfuyouapp/NetworkFileDownloader.java
- students/com1714080901237/app/src/main/java/com/example/eduhuzappfuyouapp/SAXService.java
- students/com1714080901237/app/src/main/res/layout/activity02_com1714080901237.xml
- students/com1714080901237/app/src/main/res/layout/activity03_com1714080901237.xml
- students/com1714080901237/app/src/main/res/layout/activity_com1714080901237.xml
- students/com1714080901237/app/src/main/res/layout/activity_file_storage.xml
这次整合实验，我主要对先前的数据储存进行了修改（其他的只有小调整），也补上了先前没有完成的xml数据储存模式，原本使用txt文本储存的数据，现在改成了xml格式。
这是前面实验的效果图：
这是现在的效果图：
数据的形式完全不同，明显更加有序，也方便后期的修改，利用。
> #8 #332 实验八整合前面的实验

- students/soft1714080902203/shiyan6/MyApplication4/.idea/codeStyles/Project.xml
- students/soft1714080902203/shiyan6/MyApplication4/.idea/vcs.xml
- students/soft1714080902203/shiyan8/MyApplication4/app/src/main/AndroidManifest.xml
- students/soft1714080902203/shiyan8/MyApplication4/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902203/Soft1714080902203Activity.java
- students/soft1714080902203/shiyan8/MyApplication4/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902203/Soft1714080902203Activity1.java
- students/soft1714080902203/shiyan8/MyApplication4/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902203/Soft1714080902203Activity2.java
- students/soft1714080902203/shiyan8/MyApplication4/app/src/main/res/layout/soft_1714080902203_activity.xml
- students/soft1714080902203/shiyan8/MyApplication4/app/src/main/res/layout/soft_1714080902203_activity1.xml
- students/soft1714080902203/shiyan8/MyApplication4/app/src/main/res/layout/soft_1714080902203_activity2.xml
> #8 #262 提交实验八代码

- students/soft1707080714328/app/src/main/AndroidManifest.xml
- students/soft1707080714328/app/src/main/java/ezu/hzuapps/androidlabs/soft1707080714328/Soft1707080714328Activity_First.java
使用了一个google的开源库zxing库实现了扫描二维码的功能
> #7 #274 第7次实验

- students/soft1714080902225/shiyan8/MyApplication000/app/src/main/java/com/example/myapplication000/Soft1714080902225_1.java
- students/soft1714080902225/shiyan8/MyApplication000/app/src/main/java/com/example/myapplication000/Soft1714080902225_2.java
- students/soft1714080902225/shiyan8/MyApplication000/app/src/main/java/com/example/myapplication000/Soft1714080902225_3.java
- students/soft1714080902225/实验八/MyApplication000/app/src/main/java/com/example/myapplication000/Soft1714080902225_1.java
- students/soft1714080902225/实验八/MyApplication000/app/src/main/java/com/example/myapplication000/Soft1714080902225_2.java
- students/soft1714080902225/实验八/MyApplication000/app/src/main/java/com/example/myapplication000/Soft1714080902225_3.java
1.跳转页面，查看详情
2.网络获取图片
3.实现摇一摇功能
> #8 #263 第八次实验

- students/soft1714080902110/edu/hzuapps/androidlabs/soft1714080902110/Game.java
- students/soft1714080902110/edu/hzuapps/androidlabs/soft1714080902110/Number.java
- students/soft1714080902110/edu/hzuapps/androidlabs/soft1714080902110/RankList.java
- students/soft1714080902110/edu/hzuapps/androidlabs/soft1714080902110/RankListSQLHelper.java
- students/soft1714080902110/res/layout/activity_game.xml
- students/soft1714080902110/res/layout/activity_rank_list.xml
- students/soft1714080902110/res/values/strings.xml
程序完整代码已传至github
https://github.com/HanXuanMo/GuessNumber
> #8 #267 提交大作业

- students/soft1714080902135/text_08/AndroidManifest.xml
- students/soft1714080902135/text_08/MainActivity.java
- students/soft1714080902135/text_08/OneclickRegistrationActivity.java
- students/soft1714080902135/text_08/ReportQueryActivity.java
- students/soft1714080902135/text_08/activity_main.xml
- students/soft1714080902135/text_08/onclick_registraction_activity.xml
- students/soft1714080902135/text_08/report_query.xml
> #8 #596 提交全部完整代码+界面

- students/soft1714080902218/java/edu/hzuapps/androidlabs/soft1714080902218/TrdActivity.java
- students/soft1714080902218/res/layout/trd_activity.xml
> #5 第五次实验 #836

- students/soft1714080902325/app5/src/main/AndroidManifest.xml
- students/soft1714080902325/app5/src/main/java/edu/hzuapps/androidlabs/soft1714080902325/CunchuActivity.java
- students/soft1714080902325/app5/src/main/java/edu/hzuapps/androidlabs/soft1714080902325/HomeActivity.java
- students/soft1714080902325/app5/src/main/java/edu/hzuapps/androidlabs/soft1714080902325/MainActivity.java
- students/soft1714080902325/app5/src/main/res/layout/activity_cunchu.xml
- students/soft1714080902325/app5/src/main/res/layout/activity_home.xml
- students/soft1714080902325/app6/src/main/AndroidManifest.xml
- students/soft1714080902325/app6/src/main/java/edu/hzuapps/androidlabs/soft1714080902325/HomeActivity.java
- students/soft1714080902325/app6/src/main/java/edu/hzuapps/androidlabs/soft1714080902325/MusicActivity.java
- students/soft1714080902325/app6/src/main/res/layout/activity_music.xml
> #5 #279 实验五代码
